# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-b09a5bbd-396d-4ce6-a15f-989ed1554773";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-b09a5bbd-396d-4ce6-a15f-989ed1554773".device = "/dev/disk/by-uuid/b09a5bbd-396d-4ce6-a15f-989ed1554773";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AD21-89FE";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-a2df8182-4853-442b-ba7c-6ca18af8696a";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
