{
  config,
  pkgs,
  lib,
  inputs,
  ...
}: let
  wallpaperContracts = import ./wallpaper/contracts.nix;
  monitorIdentity = wallpaperContracts.dmsMonitorIdentity;
  wallpaperTransitionContract = wallpaperContracts.wallpaperTransitions;
  dmsWallpaperSessionSync = wallpaperContracts.dmsWallpaperSessionSync;
  skwdColorContract = wallpaperContracts.skwdColorContract;
  skwdWallBase = import ./skwd-wall-package.nix {inherit pkgs inputs;};
  homeDir = config.home.homeDirectory;
  steamLibraryDir = "${homeDir}/games/SteamLibrary";
  steamWorkshopDir = "${steamLibraryDir}/steamapps/workshop/content/431960";
  steamWeAssetsDir = "${steamLibraryDir}/steamapps/common/wallpaper_engine/assets";
  skwdScriptDir = "${homeDir}/.config/skwd-wall/scripts";
  skwdSecretsFile = "${homeDir}/.config/skwd-wall/secrets.env";
  skwdDefaultMonitor = monitorIdentity.primary.connector;
  defaultWallpaperTransition = wallpaperTransitionContract.default;
  allowedWallpaperTransitionsJson = builtins.toJSON wallpaperTransitionContract.allowed;
  includedWallpaperTransitionsJson = builtins.toJSON wallpaperTransitionContract.included;
  dmsWallpaperSessionSyncJson = builtins.toJSON dmsWallpaperSessionSync;

  applyHelpers = import ./wallpaper/apply-helpers.nix {
    inherit pkgs defaultWallpaperTransition;
  };
  inherit (applyHelpers) skwdApplyStaticWallpaper;

  skwdWeCaptureStill =
    (
      import ./wallpaper/we-capture-still.nix {
        inherit pkgs steamWeAssetsDir steamWorkshopDir;
      }
    )
    .skwdWeCaptureStill;

  skwdWallPkg =
    (
      import ./wallpaper/patched-package.nix {
        inherit
          pkgs
          skwdWallBase
          skwdApplyStaticWallpaper
          steamWorkshopDir
          steamWeAssetsDir
          skwdSecretsFile
          ;
      }
    )
    .skwdWallPkg;

  skwdPrepareState =
    (
      import ./wallpaper/skwd-wall-state.nix {
        inherit
          pkgs
          skwdColorContract
          skwdWallPkg
          skwdDefaultMonitor
          skwdScriptDir
          steamLibraryDir
          steamWorkshopDir
          steamWeAssetsDir
          skwdSecretsFile
          ;
      }
    )
    .skwdPrepareState;

  skwdDmsSyncHook =
    (
      import ./wallpaper/dms-greeter-sync.nix {
        inherit
          pkgs
          lib
          skwdWallPkg
          skwdWeCaptureStill
          dmsWallpaperSessionSyncJson
          allowedWallpaperTransitionsJson
          includedWallpaperTransitionsJson
          defaultWallpaperTransition
          ;
      }
    )
    .skwdDmsSyncHook;
in {
  home.packages = [skwdWallPkg skwdWeCaptureStill];

  xdg.configFile."skwd-wall/scripts/sync-dms-wallpaper.sh".source = skwdDmsSyncHook;

  home.activation.ensureWritableSkwdConfig = lib.hm.dag.entryAfter ["writeBoundary"] ''
    run ${skwdPrepareState}
  '';

  home.activation.cleanupLegacySkwdDaemonLivefix = lib.hm.dag.entryAfter ["writeBoundary"] ''
    legacy_skwd_daemon="$HOME/.local/bin/skwd-daemon-livefix"
    if [ -e "$legacy_skwd_daemon" ] || [ -L "$legacy_skwd_daemon" ]; then
      run rm -f "$legacy_skwd_daemon"
    fi

    legacy_skwd_dropin="$HOME/.config/systemd/user/skwd-daemon.service.d/livefix.conf"
    if [ -e "$legacy_skwd_dropin" ] || [ -L "$legacy_skwd_dropin" ]; then
      run rm -f "$legacy_skwd_dropin"
    fi

    legacy_skwd_dropin_dir="$HOME/.config/systemd/user/skwd-daemon.service.d"
    if [ -d "$legacy_skwd_dropin_dir" ] && [ -z "$(${pkgs.findutils}/bin/find "$legacy_skwd_dropin_dir" -mindepth 1 -print -quit)" ]; then
      run rmdir "$legacy_skwd_dropin_dir"
    fi
  '';

  # Include dynamic Zathura color file generated by skwd-wall's matugen
  programs.zathura.extraConfig = "include skwd-colors";

  systemd.user.services.skwd-daemon = {
    Unit = {
      Description = "skwd wallpaper daemon";
      After = ["hyprland-session.target"];
      PartOf = ["hyprland-session.target"];
    };
    Service = {
      Type = "simple";
      ExecStartPre = [
        "${pkgs.coreutils}/bin/mkdir -p %t/skwd"
        "-${pkgs.coreutils}/bin/rm -f %t/skwd/daemon.sock"
      ];
      ExecStart = "${skwdWallPkg}/bin/skwd-daemon";
      Restart = "on-failure";
      RestartSec = "2";
    };
    Install = {
      WantedBy = ["hyprland-session.target"];
    };
  };
}
